#!/bin/bash

set -xe

GOOS=darwin GOARCH=amd64 go build -o ls-go-darwin-amd64

GOOS=linux GOARCH=amd64 go build -o ls-go-linux-amd64
GOOS=linux GOARCH=386 go build -o ls-go-linux-386
GOOS=linux GOARCH=arm64 go build -o ls-go-linux-arm64

#GOOS=windows GOARCH=amd64 go build -o ls-go-windows-amd64
#GOOS=windows GOARCH=386 go build -o ls-go-windows-386
